### ISSUE TITLE
Dados de uso

### ISSUE THREAD

**Issue by vmesel** [fbidu/impeachment-cloud#1]
Opa, você teria como me passar os dados que você usou para processamento para eu poder utiliza-los para machine learning.

**Comment by fbidu** [comment]
Oi @vmesel 

Claro, os dados estão no repositório inclusive. São os arquivos `csv` e `txt`. Mais explicitamente:
- [Todos os votos - votes.csv](https://github.com/fbidu/impeachment-cloud/blob/master/votes.csv)
- [Todos os discursos - speeches-only.txt](https://github.com/fbidu/impeachment-cloud/blob/master/speeches-only.txt)

Depois tem arquivos para análises dos votos das mulheres, dos homens, dos votos favoráveis e contrários. No entanto, todos eles são calculados com base no `votes.csv`

Se precisar de mais informações, pode reabrir a issue.

Nota: no site da câmara tem uma parte em que você pode baixar a ata e a transcrição de qualquer sessão
